# These command aliases are not final, may change
[alias]
# Alias to build actual plugin binary for the specified target.
prepublish = "build --target wasm32-wasip1"

[target.'cfg(target_arch = "wasm32")']
rustflags = ["--cfg=swc_ast_unknown"]
