[package]
authors = ["Mathis MÃ¸ller"]
description = "Common code for jotai SWC plugins"
license = "MIT"
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_common = "0.29.4"
swc_core = { version = "0.28.19", features = ["ecma_ast"] }
